# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build, > result.output
          echo test, and deploy your project. > result.output
          
      - name: Upload a Build Artifact
        id: upload_build_artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: upload_artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: result.output
      # - name: Comment current pull request
      #   # You may pin to the exact commit or the version.
      #   # uses: alawiii521/current-pr-comment@4d4d98a002a3994cb185d1e28e909bfabb0585f0
      #   uses: alawiii521/current-pr-comment@v1.0
      #   with:
      #     # Github token
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     # Comment
      #     comment: "Please Open the upload artifacts for detail of the changes"
      - name: Print
        if: steps.upload_build_artifact.outputs == contains('Artifact upload_artifact has been successfully uploaded!')  # Check for success string in output
        run: |
          echo ${{steps.upload_build_artifact.outputs}}
      - name: Comments on PR 
        uses: mshick/add-pr-comment@v2
        if: always()
        with:
          message: |
            **Howdie!**

          message-failure: |
            Uh oh!
